name: @@NAME@@
version: @@VERSION@@
summary: Code editing. Redefined.
description: |
  Visual Studio Code is a new choice of tool that combines the
  simplicity of a code editor with what developers need for the core
  edit-build-debug cycle.

architectures:
  - build-on: amd64
    run-on: @@ARCHITECTURE@@
compression: lzo

grade: stable
confinement: classic
base: core18

parts:
  code:
    plugin: dump
    source: .
    stage-packages:
      - ibus-gtk3
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgbm1
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxss1
      - libxtst6
      - zlib1g
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
  gtk-common-themes:
    plugin: nil
    build-packages:
      - snapd
    override-pull: |
      set -eu
      snap download gtk-common-themes --edge
      unsquashfs gtk-common-themes*.snap
    override-build: |
      set -eu
      [ -d squashfs-root/ ] || exit 1
      cp -a squashfs-root/* $SNAPCRAFT_PART_INSTALL/
  gnome-platform:
    plugin: nil
    build-packages:
      - snapd
    override-pull: |
      set -eu
      snap download gnome-3-34-1804 --edge
      unsquashfs gnome-*.snap
    override-build: |
      set -eu
      [ -d squashfs-root/ ] || exit 1
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
      cp -a squashfs-root/* $SNAPCRAFT_PART_INSTALL/gnome-platform

apps:
  @@NAME@@:
    command: electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --no-sandbox
    common-id: @@NAME@@.desktop
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/@@NAME@@/bin/@@NAME@@ --open-url --no-sandbox
    environment:
      DISABLE_WAYLAND: 1
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

environment:
  GTK_USE_PORTAL: '1'
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
